
import { Language } from './types';

export const SYSTEM_INSTRUCTIONS = `
You are a medical report analysis assistant specialized in explaining blood/sugar, heart-related, imaging (CT/MRI/USG), and endoscopy reports.
Your role is to EXPLAIN results in simple, neutral, educational language.

CRITICAL RULES:
1. PRIMARY LANGUAGE: Respond primarily in Bangla using very simple, easy-to-understand words.
2. MEDICAL TERMS: For every English medical term, abbreviation, or marker (e.g., HbA1c, EF, Gastritis, CT Scan, Lesion), you MUST include a simple Bangla explanation in brackets immediately after it.
   Example: "HbA1c (গত ৩ মাসের রক্তে চিনির গড় মাত্রা)", "EF (হার্টের পাম্প করার ক্ষমতা)", "Gastritis (পাকস্থলীর প্রদাহ বা গ্যাস্ট্রিকের সমস্যা)", "Lesion (শরীরের কোনো অংশে অস্বাভাবিক পরিবর্তন বা ক্ষত)"
3. DO NOT diagnose diseases. NEVER say "the patient has [disease]" or confirm any diagnosis.
4. Use cautious, non-alarming phrasing: "may indicate (হয়তো নির্দেশ করে)", "suggests (ইঙ্গিত দেয়)", "findings associated with... (এর সাথে সম্পর্কিত ফলাফল)".
5. Tone: Calm, respectful, and educational. Support both Bangla and English (but default to simple Bangla).

OUTPUT STRUCTURE:
1. Report Summary: High-level overview (in simple Bangla).
2. Important Findings: List markers/findings with the bracketed explanation format.
3. Educational Context: What these findings MAY indicate (educational only).
4. Next Steps: Recommend specific specialists (e.g., Cardiologist, Gastroenterologist).
5. Disclaimer: You MUST end with the EXACT following text (In English, followed by the Bangla translation):
"Disclaimer:
This analysis is generated by an AI system for educational purposes only.
It is NOT a medical diagnosis.
Please consult a qualified doctor for accurate diagnosis and treatment."

Current requested language: {{LANGUAGE}}
`;

export const CHAT_SYSTEM_INSTRUCTION = `
You are a helpful medical information assistant. 
1. Talk to the user in simple Bangla. 
2. If they use English medical terms, explain them in brackets.
3. NEVER provide a diagnosis or prescription. 
4. Always suggest consulting a doctor for any specific health concerns.
5. Be respectful and calm.
`;

export const UI_STRINGS: Record<Language, any> = {
  en: {
    title: 'MediClarify',
    subtitle: 'AI explanations for your medical reports.',
    tabAnalysis: 'Analysis',
    tabChat: 'Chat Bot',
    tabLive: 'Live Voice',
    tabHistory: 'History',
    uploadLabel: 'Upload Report (Photo)',
    uploadHint: 'Upload a clear photo of your Blood, Heart, Imaging, or Endoscopy report.',
    analyzing: 'Analyzing report details...',
    btnAnalyze: 'Start Analysis',
    btnReset: 'New Report',
    language: 'বাংলা',
    copy: 'Copy Result',
    copied: 'Copied!',
    download: 'Download PDF',
    disclaimerTitle: 'Medical Disclaimer',
    disclaimerText: 'This analysis is generated by an AI system for educational purposes only. It is NOT a medical diagnosis. Please consult a qualified doctor for accurate diagnosis and treatment.',
    resultsTitle: 'Your Analysis Result',
    errorTitle: 'Analysis Error',
    errorDesc: 'Could not process the report. Please ensure the photo is clear and contains readable text.',
    consultDoctor: 'Always consult a licensed physician to interpret these findings.',
    chatPlaceholder: 'Ask a medical question...',
    liveStart: 'Start Voice Conversation',
    liveStop: 'Stop Conversation',
    liveStatus: 'Connected & Listening...',
    liveInstruction: 'You can talk to the AI now. Speak clearly about your health concerns.',
    historyTitle: 'Report History',
    emptyHistory: 'No reports saved yet.',
    delete: 'Delete'
  },
  bn: {
    title: 'মেডি-ক্লারিফাই',
    subtitle: 'আপনার মেডিকেল রিপোর্ট সহজে বুঝে নিন।',
    tabAnalysis: 'রিপোর্ট বিশ্লেষণ',
    tabChat: 'চ্যাট বট',
    tabLive: 'সরাসরি কথা',
    tabHistory: 'ইতিহাস',
    uploadLabel: 'রিপোর্ট আপলোড করুন (ছবি)',
    uploadHint: 'আপনার রক্ত পরীক্ষা, হার্ট, ইমেজিং বা এন্ডোস্কোপি রিপোর্টের পরিষ্কার ছবি আপলোড করুন।',
    analyzing: 'রিপোর্ট বিশ্লেষণ করা হচ্ছে...',
    btnAnalyze: 'বিশ্লেষণ শুরু করুন',
    btnReset: 'নতুন রিপোর্ট',
    language: 'English',
    copy: 'কপি করুন',
    copied: 'কপি হয়েছে!',
    download: 'ডাউনলোড পিডিএফ',
    disclaimerTitle: 'চিকিৎসা সংক্রান্ত সতর্কতা',
    disclaimerText: 'এই বিশ্লেষণটি শুধুমাত্র শিক্ষামূলক উদ্দেশ্যে একটি এআই সিস্টেম দ্বারা তৈরি করা হয়েছে। এটি কোনো চিকিৎসা রোগ নির্ণয় নয়। সঠিক রোগ নির্ণয় এবং চিকিৎসার জন্য অনুগ্রহ করে একজন যোগ্য চিকিৎসকের সাথে পরামর্শ করুন।',
    resultsTitle: 'আপনার রিপোর্টের ব্যাখ্যা',
    errorTitle: 'বিশ্লেষণে ত্রুটি',
    errorDesc: 'রিপোর্টটি প্রসেস করা সম্ভব হয়নি। অনুগ্রহ করে নিশ্চিত করুন যে ছবিটি পরিষ্কার এবং লেখাগুলো পড়া যাচ্ছে।',
    consultDoctor: 'ফলাফলগুলি বোঝার জন্য সর্বদা একজন নিবন্ধিত চিকিৎসকের পরামর্শ নিন।',
    chatPlaceholder: 'স্বাস্থ্য বিষয়ক প্রশ্ন করুন...',
    liveStart: 'ভয়েস কথোপকথন শুরু করুন',
    liveStop: 'কথোপকথন বন্ধ করুন',
    liveStatus: 'সংযুক্ত এবং শুনছে...',
    liveInstruction: 'আপনি এখন সরাসরি এআই এর সাথে কথা বলতে পারেন। আপনার স্বাস্থ্য সমস্যা নিয়ে পরিষ্কারভাবে কথা বলুন।',
    historyTitle: 'রিপোর্ট ইতিহাস',
    emptyHistory: 'এখনও কোনো রিপোর্ট নেই।',
    delete: 'মুছে ফেলুন'
  }
};
