
import { Language } from './types';

export const SYSTEM_INSTRUCTIONS = `
You are a medical report analysis assistant specialized in explaining blood/sugar, heart-related, imaging (CT/MRI/USG), and endoscopy reports.
Your role is to EXPLAIN results in simple, neutral, educational language.

CRITICAL RULES:
1. PRIMARY LANGUAGE: Respond primarily in Bangla using very simple, easy-to-understand words.
2. MEDICAL TERMS: For every English medical term, abbreviation, or marker (e.g., HbA1c, EF, Gastritis, CT Scan, Lesion), you MUST include a simple Bangla explanation in brackets immediately after it.
   Example: "HbA1c (গত ৩ মাসের রক্তে চিনির গড় মাত্রা)", "EF (হার্টের পাম্প করার ক্ষমতা)", "Gastritis (পাকস্থলীর প্রদাহ বা গ্যাস্ট্রিকের সমস্যা)", "Lesion (শরীরের কোনো অংশে অস্বাভাবিক পরিবর্তন বা ক্ষত)"
3. DO NOT diagnose diseases. NEVER say "the patient has [disease]" or confirm any diagnosis.
4. Use cautious, non-alarming phrasing: "may indicate (হয়তো নির্দেশ করে)", "suggests (ইঙ্গিত দেয়)", "findings associated with... (এর সাথে সম্পর্কিত ফলাফল)".
5. Tone: Calm, respectful, and educational. Support both Bangla and English (but default to simple Bangla).

OUTPUT STRUCTURE (MANDATORY HEADERS):
### SUMMARY: A high-level overview in simple Bangla.
### KEY FINDINGS: List markers/findings with the bracketed explanation format.
### EXPLANATIONS: Simple educational context for what these findings may indicate.
### RECOMMENDATIONS: Suggest next steps and specific specialists (e.g., Cardiologist).
### DISCLAIMER: The mandatory medical warning.

Always conclude with the exact disclaimer text provided in your instructions.

Current requested language: {{LANGUAGE}}
`;

export const CHAT_SYSTEM_INSTRUCTION = `You are a friendly and helpful medical assistant for MediClarify. 
Your goal is to explain medical concepts simply and help with health-related queries.
CRITICAL: Always use the language requested: {{LANGUAGE}}.
Always include a disclaimer that you are an AI and not a doctor.`;

export const UI_STRINGS: Record<Language, any> = {
  en: {
    title: 'MediClarify',
    subtitle: 'AI explanations for your medical reports.',
    tabAnalysis: 'Analysis',
    tabHistory: 'History',
    tabPremium: 'Premium',
    uploadLabel: 'Upload Report (Photo)',
    uploadHint: 'Upload a clear photo of your Blood, Heart, Imaging, or Endoscopy report.',
    analyzing: 'Analyzing report details...',
    btnAnalyze: 'Start Analysis',
    btnReset: 'New Report',
    language: 'বাংলা',
    copy: 'Copy Result',
    copied: 'Copied!',
    download: 'Download Report (PDF)',
    disclaimerTitle: 'Medical Disclaimer',
    disclaimerText: 'This analysis is generated by an AI system for educational purposes only. It is NOT a medical diagnosis. Please consult a qualified doctor for accurate diagnosis and treatment.',
    resultsTitle: 'Your Analysis Result',
    errorTitle: 'Analysis Error',
    errorDesc: 'Could not process the report. Please ensure the photo is clear and contains readable text.',
    consultDoctor: 'Always consult a licensed physician to interpret these findings.',
    historyTitle: 'Report History',
    emptyHistory: 'No reports saved yet.',
    delete: 'Delete',
    view: 'View',
    pricingTitle: 'Unlock Premium Features',
    monthly: 'Monthly Plan',
    yearly: 'Yearly Plan',
    priceMonthly: '৳500 / month',
    priceYearly: '৳5000 / year',
    subscribe: 'Subscribe Now',
    paymentSuccess: 'Subscription Activated Successfully!',
    processingPayment: 'Redirecting to Payment Gateway...',
    limitReached: 'Free limit reached. Please upgrade to Premium to analyze more reports.',
    verifyBtn: 'Verify Payment',
    verifyPlaceholder: 'Enter Transaction ID (e.g., 8N7K9L2P)',
    verifying: 'Verifying Transaction...',
    invalidTrx: 'Invalid Transaction ID. Please check and try again.',
    manualTitle: 'Official Payment Channels',
    stepGuide: 'How to Pay? (Step-by-Step Guide)',
    chatPlaceholder: 'Ask anything about your report...',
    liveStatus: 'Listening...',
    liveStart: 'Start Voice Chat',
    liveInstruction: 'Talk to our AI assistant in real-time about your health.',
    liveStop: 'Stop Voice Chat'
  },
  bn: {
    title: 'মেডি-ক্লারিফাই',
    subtitle: 'আপনার মেডিকেল রিপোর্ট সহজে বুঝে নিন।',
    tabAnalysis: 'রিপোর্ট বিশ্লেষণ',
    tabHistory: 'ইতিহাস',
    tabPremium: 'প্রিমিয়াম',
    uploadLabel: 'রিপোর্ট আপলোড করুন (ছবি)',
    uploadHint: 'আপনার রক্ত পরীক্ষা, হার্ট, ইমেজিং বা এন্ডোস্কোপি রিপোর্টের পরিষ্কার ছবি আপলোড করুন।',
    analyzing: 'রিপোর্ট বিশ্লেষণ করা হচ্ছে...',
    btnAnalyze: 'বিশ্লেষণ শুরু করুন',
    btnReset: 'নতুন রিপোর্ট',
    language: 'English',
    copy: 'কপি করুন',
    copied: 'কপি হয়েছে!',
    download: 'রিপোর্ট ডাউনলোড (PDF)',
    disclaimerTitle: 'চিকিৎসা সংক্রান্ত সতর্কতা',
    disclaimerText: 'এই বিশ্লেষণটি শুধুমাত্র শিক্ষামূলক উদ্দেশ্যে একটি এআই সিস্টেম দ্বারা তৈরি করা হয়েছে। এটি কোনো চিকিৎসা রোগ নির্ণয় নয়। সঠিক রোগ নির্ণয় এবং চিকিৎসার জন্য অনুগ্রহ করে একজন যোগ্য চিকিৎসকের সাথে পরামর্শ করুন।',
    resultsTitle: 'আপনার রিপোর্টের ব্যাখ্যা',
    errorTitle: 'বিশ্লেষণে ত্রুটি',
    errorDesc: 'রিপোর্টটি প্রসেস করা সম্ভব হয়নি। অনুগ্রহ করে নিশ্চিত করুন যে ছবিটি পরিষ্কার এবং লেখাগুলো পড়া যাচ্ছে।',
    consultDoctor: 'ফলাফলগুলি বোঝার জন্য সর্বদা একজন নিবন্ধিত চিকিৎসকের পরামর্শ নিন।',
    historyTitle: 'রিপোর্ট ইতিহাস',
    emptyHistory: 'এখনও কোনো রিপোর্ট নেই।',
    delete: 'মুছে ফেলুন',
    view: 'দেখুন',
    pricingTitle: 'প্রিমিয়াম ফিচার আনলক করুন',
    monthly: 'মাসিক প্ল্যান',
    yearly: 'বার্ষিক প্ল্যান',
    priceMonthly: '৫০০ টাকা / মাস',
    priceYearly: '৫০০০ টাকা / বছর',
    subscribe: 'সাবস্ক্রাইব করুন',
    paymentSuccess: 'সাবস্কৃপশন সফলভাবে সক্রিয় হয়েছে!',
    processingPayment: 'পেমেন্ট গেটওয়েতে পাঠানো হচ্ছে...',
    limitReached: 'ফ্রি লিমিট শেষ হয়েছে। আরও রিপোর্ট বিশ্লেষণের জন্য প্রিমিয়ামে আপগ্রেড করুন।',
    verifyBtn: 'পেমেন্ট ভেরিফাই করুন',
    verifyPlaceholder: 'ট্রানজেকশন আইডি দিন (যেমন: 8N7K9L2P)',
    verifying: 'ভেরিফাই করা হচ্ছে...',
    invalidTrx: 'ভুল ট্রানজেকশন আইডি। অনুগ্রহ করে আবার চেষ্টা করুন।',
    manualTitle: 'অফিসিয়াল পেমেন্ট চ্যানেল',
    stepGuide: 'কীভাবে পেমেন্ট করবেন? (ধাপে ধাপে গাইড)',
    chatPlaceholder: 'রিপোর্ট সম্পর্কে কিছু জিজ্ঞাসা করুন...',
    liveStatus: 'শুনছি...',
    liveStart: 'ভয়েস চ্যাট শুরু করুন',
    liveInstruction: 'আপনার স্বাস্থ্য নিয়ে রিয়েল-টাইমে এআইয়ের সাথে কথা বলুন।',
    liveStop: 'ভয়েস চ্যাট বন্ধ করুন'
  }
};
